sqlbrite/src/androidTest/java/com/squareup/sqlbrite/SqlBriteContentProviderTests.java
sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBriteContentProvider.java

- Expose the same Logger/Query api that SqlBrite does
- Wrap ContentResolver database operations
Closes #13

Module for a ContentResolver wrapper

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java

So that transactions dont require a catch clause.

Omit the IOException from close()

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/QueryObservableTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryObservable.java

Now `Query.toString()` will be part of the exception stack trace for `QueryObservable.mapToList()`.
Plus 2 little unit tests to assert that `QueryObservable` respects the `Observable` contract at least for errors.

Add Query to the cause of exception in QueryObservable

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryObservable.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryToListOperator.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryToOneOperator.java

Queries returning single items is very common. It's not too terrible to do this yourself with Query#asRows, but we can provide something even more readable at little inconvenience.
cc @danh32

Provide convenience operators for mapping to a single item.

---

sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java

These do not play well with various combinations of lint, RxJava, and retrolambda and result in false-positives.

Comment out worker thread annotations for now.

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryObservable.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryToOneOperator.java

mapToOneOrNull replaced by mapToOneOrDefault

---

sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java

This was in my working directory, although I don't remember doing it. Saves 8 bytes per object instance if I counted right (but I also didn't try that hard to count).

Save some bytes in the object header by inlining set.

---

sqlbrite/src/main/java/com/squareup/sqlbrite/BackpressureBufferLastOperator.java

The fields are already "Guarded by 'this'".

Remove unnecessary volatile keyword being used

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/QueryTest.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/TestDb.java
sqlbrite/src/main/java/com/squareup/sqlbrite/QueryObservable.java
sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java

These match the convenience methods on QueryObservable, but are available for use later in the stream (e.g., after a take() operator) via lift().
Closes #69.

Expose static mapping operators on Query.

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java

This ensures that even with backpressure enabled to suppress initial emission an error is still thrown.

Check for enclosing transaction on actual subscribe, not initial emission.

---

sample/src/main/java/com/example/sqlbrite/todo/db/DbModule.java
sample/src/main/java/com/example/sqlbrite/todo/ui/ItemsFragment.java
sample/src/main/java/com/example/sqlbrite/todo/ui/ListsFragment.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteContentResolverTest.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/QueryTest.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/TestScheduler.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java

This has two positive effects:
- Threads which commit transactions no longer wait on downstream-triggered queries to run.
- Initial and triggered notifications now happen on the same scheduler (actually the same worker, too) which was potentially tricky to get correct before.
Closes #84.

Take an emission scheduler when creating wrapper types.

---

sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java

Before:
```
Database  V  QUERY (0ms)
V    tables: todo_list
V    sql: SELECT name
V  FROM todo_list
V  WHERE _id = ?
V    args: [2]
V  QUERY (0ms)
V    tables: todo_item
V    sql: SELECT COUNT(*)
V  FROM todo_item
V  WHERE complete = 0
V  AND todo_list_id = ?
V    args: [2]
V  QUERY (0ms)
V    tables: todo_item
V    sql: SELECT *
V  FROM todo_item
V  WHERE todo_list_id = ?
V  ORDER BY complete ASC
V    args: [2]
```
After:
```
Database  V  QUERY (0ms)
V    tables: todo_list
V    sql: SELECT name
V         FROM todo_list
V         WHERE _id = ?
V    args: [2]
V  QUERY (0ms)
V    tables: todo_item
V    sql: SELECT COUNT(*)
V         FROM todo_item
V         WHERE complete = 0
V         AND todo_list_id = ?
V    args: [2]
V  QUERY (0ms)
V    tables: todo_item
V    sql: SELECT *
V …
```

Indent queries when logging.

---

README.md

The BriteContentResolver example is missing the Schedulers argument. Similar to the wrapDatabaseHelper example, I've added Schedulers.io() as an argument.

Add Scheduler argument to BriteContentResolver example

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteContentResolverTest.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java

Schedulers apply backpressure upstream which previously behaved as an unbounded stream. When the scheduler worker couldn't keep up an MBPE was thrown. We already use the 'latest' strategy for slowing 'Query' emissions after the scheduler so we can apply the same thing before it.
This comes with a subtle change in that transactions will now synchronously run every filter Func before continuing. Previously the filters ran on the scheduler and did not block the thread performing the transaction. This means that the more queries that are listening at once, the slower every transaction's completing step will be. I don't expect this to have any meaningful impact since it's very fast and happening on a background thread already.

Guard against a slow scheduler with backpressure strategy.

---

sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java

Rather than a bunch of allocations to create and concat two streams (which startWith does) just move the initial emission to our custom observable.

Trigger initial query with less overhead.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java

Still requires you have an instance of `SQLiteDatabase` to call `compileStatement` on but I don't think it makes sense to copy that API over.

Add SQLiteStatement insert/update/delete commands which send table triggers

---

README.md

Just update the README so that it doesn't use deprecated `SqlBrite.create()`  method

Update README to use builder

---

build.gradle

This allows relative project dependencies to appear correctly in the generated Maven pom.
Closes #193.

Ensure a group and version is defined for all modules.

---

.travis.yml
gradle/start-emulator.sh
sqlbrite/build.gradle

We're going to have two modules running tests now so this optimization is harder to do (with diminishing returns).

Move emulator startup into Travis.

---

sample/src/main/java/com/example/sqlbrite/todo/ui/ItemsFragment.java
sample/src/main/java/com/example/sqlbrite/todo/ui/NewItemFragment.java
sample/src/main/java/com/example/sqlbrite/todo/ui/NewListFragment.java
sqlbrite/src/androidTest/java/com/squareup/sqlbrite3/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite3/BriteDatabase.java
sqlbrite/src/main/java/com/squareup/sqlbrite3/SqlBrite.java

* Remove overloads which did not take a conflict resolution strategy. Force the caller to always specify (matches SupportSQLiteDatabase).
* Remove @RequiresApi(HONEYCOMB) as we're now minSdk = 14.
* Replace Javadoc references from framework classes to support library classes where available.
* Restore use of Subject now that there is no interop bridge.

API cleanups.

---

sqlbrite/src/androidTest/java/com/squareup/sqlbrite3/BriteDatabaseTest.java
sqlbrite/src/main/java/com/squareup/sqlbrite3/BriteDatabase.java

Add tests for indents in all 4 arbitrary SQL string methods.
Remove timing of these queries. It's unlikely to reflect any real measure of performance due to internal program caching and lazy windowing of results.

Indent execute() SQL statements in logs.
