square/sqlbrite

- .travis.yml
- gradle/gradle-mvn-push.gradle
- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/SqlBriteTest.java
> Add Travis secrets for snapshot deployment.

- sqlbrite-sample/src/main/java/com/example/sqlbrite/todo/ui/ItemsFragment.java
- sqlbrite-sample/src/main/java/com/example/sqlbrite/todo/ui/ListsFragment.java
Semantically, view initialization better to do in `Fragment#onViewCreated()` than in `Fragment#onCreateView()` which should just create view
> Moved view initialization to Fragment#onViewCreated() in sample app

- README.md
The rawQuery method is in SQLiteDatabase not in SQLiteOpenHelper.
> Changed SQLiteOpenHelper.rawQuery reference to SQLiteDatabase.rawQuery

- build.gradle
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java
> Add @CheckResult and @WorkerThread annotations to methods.

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
> Add note about skipping initial notification emission.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
> Trigger notifications after commit.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
> Add APIs for executing raw SQL in both trigger and no-trigger forms.

- README.md
In the 'Transactions' code example, transaction.setSuccessful() is still being used. I've simply replaced this with the latest method call transaction.markSuccessful().
> Correct README.md example

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/QueryToListOperator.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/QueryToOneOperator.java
Method count drops 11 from 190 to 179. Every bit counts...
> Remove creation of synthetic accessor methods.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
This tests RxJava behavior instead of SqlBrite.
> Remove useless test.

- build.gradle
- sample/build.gradle
- sample/src/main/java/com/example/sqlbrite/todo/db/TodoItem.java
- sample/src/main/java/com/example/sqlbrite/todo/db/TodoList.java
- sample/src/main/java/com/example/sqlbrite/todo/ui/ListsItem.java
> Switch from AutoParcel to AutoValue

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
Also delegate to execute() from executeAndTrigger()
> Added logging for execute()

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/QueryTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/QueryToOneOperator.java
> Request an additional item when one is swallowed.

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
* Use single Action0 instance for every stream to check whether it is being subscribed to in a transaction.
* Promote anonymous Query subclass to named inner-class. This allows it to implement Func1 which returns itself for use as a mapper from triggered tables to the query instance.
> Reduce allocations by 2 for each createQuery call.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/QueryTest.java
- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/TestDb.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
> Non-exclusive transaction

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
This will reduce the method count by 1.
> Remove creation of synthetic accessor method.

- .travis.yml
- build.gradle
I'm here. Might as well do this now.
> Plugin 2.2.2, platform and support libs 25.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteContentResolverTest.java
- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/RecordingObserver.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteContentResolver.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java
> Add ability to apply a transformer to all returned Query Observables

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java
> Restore worker thread annotations.

- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
Expose the BriteDatabase's helper db via getWriteableDatabase.
Fixes #159
> Expose BriteDatabase#getWriteableDatabase

- sample/src/main/java/com/example/sqlbrite/todo/db/DbModule.java
I changed to use `SqlBrite.Builder` instead of `SqlBrite.create()` which is deprecated.
> Change to use Builder instead of deprecated create()

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite2/QueryTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite2/QueryToOneOperator.java
This allows us to use null to indicate whether to emit an item or not.
> Prevent mapping to null.

- build.gradle
- gradle/gradle-mvn-push.gradle
- settings.gradle
- sqlbrite-kotlin/build.gradle
- sqlbrite-kotlin/gradle.properties
- sqlbrite-kotlin/src/main/AndroidManifest.xml
- sqlbrite-kotlin/src/main/java/com/squareup/sqlbrite2/extensions.kt
> Create Kotlin module with helper extension methods.

- sqlbrite-kotlin/src/main/java/com/squareup/sqlbrite2/extensions.kt
- sqlbrite/src/androidTest/java/com/squareup/sqlbrite2/QueryTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite2/QueryObservable.java
- sqlbrite/src/main/java/com/squareup/sqlbrite2/QueryToOptionalOperator.java
- sqlbrite/src/main/java/com/squareup/sqlbrite2/SqlBrite.java
> Add mapToOptional for abstracting empty queries.

- build.gradle
Bump:
* ~~build tools from 25.0.1 to 25.0.3~~
* support lib from 25.0.1 to 25.3.1
* ~~gradle from 2.2.2 to 2.3.2~~
(addresses Android Studio warnings)
> Update build tools, support lib + gradle version

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite2/BriteDatabaseTest.java
> Fix the test which is supposed to error.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite/BriteDatabaseTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/BriteDatabase.java
- sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java
These are still packaged-scoped so we'll need to put a class into this package in the bridge, but it allows hooking up to triggers being sent as well as injecting additional triggers.
> Expose the required bits to connect 1.x and 2.x.

- build.gradle
> Kotlin 1.1.4-3.

- sqlbrite/src/androidTest/java/com/squareup/sqlbrite3/BriteDatabaseTest.java
- sqlbrite/src/main/java/com/squareup/sqlbrite3/BriteDatabase.java
Also switch to using it internally for all queries.
> Add query overloads for SupportSQLiteQuery.

- build.gradle
Also updated support library to 26.1.0 because alpha9-1 depends on that.
> update SQLite support library to alpha9-1

- sqlbrite-kotlin/src/main/java/com/squareup/sqlbrite3/extensions.kt
>  Add inTransaction convenience lambda.

- README.md
#234 
While I was at it, also updated the Gradle dependency config to `implementation` 
Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>
> Update readme to reflect new API changes

- README.md
> Replaced Action1 by Consumer in README
